### ISSUE TITLE
Crashing in VS2015 Community - Windows Forms Project

### ISSUE THREAD

**Issue by beannaich** [madskristensen/WebEssentials2015#87] opened 2015-08-23 19:24 UTC
After installing this extension in VS2015, I started getting crashes when loading a Windows Forms project. If I disable the extension, everything goes back to working as it should, and the project has a single JSON file in it (among all the other C# files).

**Comment by madskristensen** [comment] 2015-08-31 23:16
This was fixed by the Web Team in Visual Studio. It was caused by an issue in the JSON editor. The fix should be in the next update to VS2015

**Closed by madskristensen** 2015-08-31 23:16 UTC
