### ISSUE TITLE
Does not appear to be an option to turn on the Preview pane for Typescript

### ISSUE THREAD

**Issue by bobwiller** [madskristensen/WebEssentials2015#62] opened 2015-06-28 20:11 UTC
In VS 2015 RC the Tools->options WebEssentials->TypeScript option is missing.  This is with the TypeScript 1.5 beta for VS 2015 also installed.

**Comment by madskristensen** [comment] 2015-06-30 12:14
Duplicate of #53

**Closed by madskristensen** 2015-06-30 12:14 UTC
